Adds C# example
This example doesn't compile when opened in CS2022 community edition:
Class1.cs: namespace $safeprojectname$
Error CS0246 The type or namespace name 'DllExport' could not be found (are you missing a using directive or an assembly reference?)	NeoBookPlugInExample	\VisualNeo-Win-SDK\C# example\Class1.cs	46	Active