Adds Power Basic plug-in examples.
Code in this commit for example 1 contains a compilation error.
----
Error 549 in VisualNeoWin\PlugInSdk\Power Basic Examples\Example 1\TestPlugIn.bas(339:042):  BYVAL required with pointers
  Line 339: Function VerifyRegCode(Code As Asciiz Ptr) As Long